INT-2189: add cg the payment consultant
openfintechio/openfintech pull request #1193
Opened 2023-07-27 15:32 UTC by Marielle89

2023-07-30 22:48 UTC, michaelkuzyk requested changes

2023-07-30 22:48 UTC, michaelkuzyk commented on data/vendors.json
> +      "en": "The payment consultant",
The Payment Consultant
![image](https://github.com/openfintechio/openfintech/assets/28463622/f683e898-d11f-43b3-ae42-8cca388997ae)
![image](https://github.com/openfintechio/openfintech/assets/28463622/f13ae8b8-cad6-4890-a86f-9642b339a44a)

2023-07-30 22:48 UTC, michaelkuzyk commented on data/payment_providers.json
> +      "en": "The payment consultant",
The Payment Consultant
відповідно до комента на вендорах

2023-08-01 07:07 UTC, michaelkuzyk approved these changes

2023-08-01 07:31 UTC, TonyTramb approved these changes

2023-08-01 07:31 UTC, merged