INT-2283: PayForFun Impl & PayForFun Wallet Method
openfintechio/openfintech pull request #1202
Opened 2023-08-07 08:03 UTC by VladyslavKL

2023-08-08 15:06 UTC, michaelkuzyk commented on data/payout_services.json
> +    "status": "active",
а де сервіс філд на вилпату?
в рельсу виплата не пройде :)

2023-08-08 15:08 UTC, michaelkuzyk commented on data/payout_methods.json
> +    "status": "active",
Задача яка залінкована  - про платежі. Звідки виплати?

2023-08-08 15:10 UTC, michaelkuzyk requested changes

2023-08-08 15:10 UTC, michaelkuzyk commented on data/payment_providers.json
> +    "code": "pay4fun",
https://merchant.p4f.com/wp-content/uploads/2021/08/logo_merchant.png

лого з їх сайту.  для Провайдера, можна і для метода заюзати, якщо для метода не дали.

на основній сторінці - там біла свгшка, а на розділі "мерчанти" - був цей логотип

2023-08-09 07:36 UTC, VladyslavKL commented on data/payout_services.json
> +    "status": "active",
это пока просто заготовка на след задачу

2023-08-09 07:37 UTC, VladyslavKL commented on data/payout_methods.json
> +    "status": "active",
это пока просто заготовка на след задачу

2023-08-09 08:20 UTC, michaelkuzyk commented on data/payment_providers.json
> +    "code": "pay4fun",
назва норм. 
![image](https://github.com/openfintechio/openfintech/assets/28463622/f81d2458-570b-4b39-9156-98c4f41a04ae)

Просто  Провайдер сам є Вендором МЕТОДУ = волета з власною апкою для юзерів. 
Це як ЛікПей має свій Лікпей Волет.

Якщо окрім волета ще якісь власні методи провайдер має (наприклад Ваучери), то краще називати з приставкою уточненням - типу pay4fun_wallet

2023-08-09 08:21 UTC, michaelkuzyk commented on data/payout_methods.json
> +    "status": "active",
в мастер таке не треба. Потім задача пропаде, а випилювати проблематично -= треба базу руками чистити. 
мержити лише нормальні сервіси. (до того ж офт форкають)

2023-08-09 08:22 UTC, michaelkuzyk commented on data/payment_services.json
> +        "required": false,
ок

2023-08-09 08:43 UTC, michaelkuzyk approved these changes

2023-08-09 08:48 UTC, Maxym2244 approved these changes

2023-08-09 08:48 UTC, merged