PC-7841: change qiwi provider and add logo with icon
openfintechio/openfintech pull request #528
Opened 2021-07-26 09:16 UTC by Maxym2244

2021-07-26 09:35 UTC, loperd approved these changes

2021-07-26 17:55 UTC, MichaelKuzyk requested changes
icon svg - лишити. 
лого змінити

2021-07-30 12:15 UTC, loperd approved these changes

2021-07-30 15:56 UTC, MichaelKuzyk approved these changes

2021-07-30 15:56 UTC, merged