PC-7896: add github actions
openfintechio/openfintech pull request #533
Opened 2021-07-30 15:20 UTC by vfrmn

2021-08-11 15:42 UTC, dzubchik requested changes
update links to openfintech repository from own

2021-09-02 09:50 UTC, loperd commented on etc/deploy.sh
> +    git push origin master
rm

2021-09-02 16:25 UTC, vfrmn commented on etc/deploy.sh
> +    git push origin master
+

2021-09-02 16:26 UTC, vfrmn commented on etc/deploy.sh
> +    git push origin master
\+

2021-09-03 10:08 UTC, loperd approved these changes

2021-09-03 13:17 UTC, merged