PC-8391: add currency waves, payment methods and payment services
openfintechio/openfintech pull request #609
Opened 2021-11-13 12:59 UTC by Maxym2244

2021-11-15 09:26 UTC, michaelkuzyk requested changes

2021-11-15 09:26 UTC, michaelkuzyk commented on data/payment_services.json
> +    "code": "waves_coin_waves_invoice",
тут все таки лишити waves_waves_invoice.  Не знайшов вживання цієї крипти з Coin.

2021-11-15 16:13 UTC, michaelkuzyk requested changes

2021-11-15 16:13 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_max": 1000
1 000 000

2021-11-15 16:13 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_max": 1000
100 000

2021-11-16 09:30 UTC, loperd approved these changes

2021-11-16 09:32 UTC, merged