PC-8424: add 1payment connector
openfintechio/openfintech pull request #617
Opened 2021-11-25 16:18 UTC by romansavchak

2021-11-30 10:22 UTC, michaelkuzyk requested changes

2021-11-30 10:22 UTC, michaelkuzyk commented on data/vendors.json
> +      "en": "1payment",
"One Payment"

з сайту: "One Payment – это международный платежный провайдер, обслуживающий клиентов в России, Европе и по всему миру. Компания работает с 2019 года."

2021-11-30 10:22 UTC, michaelkuzyk commented on data/payment_providers.json
> +    "name": {
"One Payment"

з сайту: "One Payment – это международный платежный провайдер, обслуживающий клиентов в России, Европе и по всему миру. Компания работает с 2019 года."

2021-12-02 09:32 UTC, romansavchak commented on data/vendors.json
> +      "en": "1payment",
:white_check_mark:

2021-12-02 09:32 UTC, romansavchak commented on data/payment_providers.json
> +    "name": {
:white_check_mark:

2021-12-02 10:29 UTC, michaelkuzyk approved these changes

2021-12-02 10:29 UTC, merged