PC-8615: PG PaymentRush
openfintechio/openfintech pull request #635
Opened 2021-12-23 15:54 UTC by TonyTramb

2021-12-26 17:09 UTC, loperd commented on data/payment_services.json
> +    "code": "payment_rush_hpp",
почему не использовать слитное paymentrush, в провайдере слитно, а здесь раздельно

2021-12-29 11:38 UTC, michaelkuzyk requested changes

2021-12-29 11:38 UTC, michaelkuzyk commented on data/payment_methods.json
> +      "en": "PaymentRush",
Payment Rush

2021-12-29 11:38 UTC, michaelkuzyk commented on data/payment_providers.json
> +      "en": "PaymentRush",
Payment Rush

2021-12-29 11:38 UTC, michaelkuzyk commented on data/vendors.json
> +      "en": "PaymentRush",
Payment Rush

2021-12-29 14:56 UTC, michaelkuzyk approved these changes

2021-12-29 14:57 UTC, merged