WIP: PC-8956: add VirtualPay
openfintechio/openfintech pull request #678
Opened 2022-02-14 10:46 UTC by denysmm

2022-02-26 14:35 UTC, Pashkalab approved these changes

2022-03-04 19:52 UTC, TonyTramb commented on data/payment_services.json
> +        "example": "255742044295",
Пример не соответствует регулярке

2022-03-16 14:01 UTC, michaelkuzyk requested changes

2022-03-29 09:35 UTC, michaelkuzyk requested changes
+ змінити ЛОГО і ІКОНКИ

2022-03-29 09:35 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_max": 11475000
11490000

2022-03-29 09:35 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_max": 11475000
11490000

2022-03-29 09:35 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_max": 11475000
exponent 2

2022-03-29 09:35 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_max": 11475000
exponent 2

2022-03-29 09:35 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_min": 10,
1?

2022-03-29 09:35 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_max": 11475000
11490000
exponent 2

2022-03-29 09:35 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_min": 0.1,
exponent 2 - 0.01

2022-03-29 09:35 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_min": 10,
1?

2022-03-29 09:35 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_min": 10,
1?

2022-03-29 09:35 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_min": 1,
0.01? 
exponent 2

2022-03-29 09:35 UTC, michaelkuzyk commented on data/payment_services.json
> +    "amount_min": 10,
exponent 2
0,01?

2022-03-31 11:41 UTC, michaelkuzyk approved these changes

2022-03-31 12:05 UTC, merged