PC-9277:add upi and imps services
openfintechio/openfintech pull request #724
Opened 2022-04-18 17:01 UTC by romansavchak

2022-04-21 22:54 UTC, TonyTramb commented on data/payout_methods.json
> +    "code": "imps",
logo+icon

2022-04-21 22:54 UTC, TonyTramb commented on data/payout_methods.json
> +    "code": "upi_bank_account",
logo+icon

2022-04-22 13:39 UTC, michaelkuzyk requested changes

2022-04-22 13:39 UTC, michaelkuzyk commented on data/payout_services.json
> +        "key": "ifsc_bank_code",
назви відповідно також

2022-04-22 13:39 UTC, michaelkuzyk commented on data/payout_services.json
> +    "code": "imps_inr",
аналогічно до попереднього

2022-04-22 13:39 UTC, michaelkuzyk commented on data/payout_services.json
> +    "amount_max": 100000
ліміти до 100к в доларовому еквіваленті
зараз це 1307.73

2022-04-22 13:39 UTC, michaelkuzyk commented on data/payout_services.json
> +    "amount_max": 100000
аналогічно

2022-04-22 15:44 UTC, michaelkuzyk approved these changes

2022-04-22 15:44 UTC, merged