Feature/pc 9266 add tests
openfintechio/openfintech pull request #736
Opened 2022-05-01 13:22 UTC by vfrmn

2022-05-02 09:44 UTC, michaelkuzyk requested changes

2022-05-02 09:44 UTC, michaelkuzyk commented on data/payment_methods.json
> -      "ru": "Наличные",
перенести назву в метод-дублікат на 5960 стрічці
( "en": "CASH" замінити)

2022-05-02 09:44 UTC, michaelkuzyk commented on data/payment_methods.json
> -    "code": "alipay",
оновити дублікат що лишився:

**Description**: "Alipay helps you to connect with customers across the world. With truly innovative e-Wallet payment solutions, Alipay provides seamless payment collection and a convenient customer experience."
**Category**: alternative
**Vendor**: alipay

2022-05-02 09:44 UTC, michaelkuzyk commented on data/payment_providers.json
> -    "status": "active",
update duplicate: 

- name: Paymentwall

2022-05-02 09:44 UTC, michaelkuzyk commented on data/payment_providers.json
> -    "status": "active",
update duplicate: 

- name: Paymentwall

2022-05-02 09:44 UTC, michaelkuzyk commented on data/vendors.json
> +      "en": "Coinpayments",
CoinPayments

2022-05-03 08:23 UTC, TonyTramb commented on data/payout_services.json
> -          "en": "Enter phone number",
![image](https://user-images.githubusercontent.com/91606148/166423601-c994805f-8f9f-4cb0-85a5-4fd80fe108f1.png)
В оставшемся дубликате label и hint подправить

2022-05-03 08:50 UTC, TonyTramb commented on data/payout_methods.json
> -      "en": "KP 'Porto-Frankivsk' (Odessa)",
у дубликата англ название на украинском (не знаю насколько это критично,но всё же)

2022-05-03 11:25 UTC, michaelkuzyk approved these changes

2022-05-03 11:37 UTC, merged