PC-9442: add pg method interkassa
openfintechio/openfintech pull request #745
Opened 2022-05-10 19:19 UTC by Marielle89

2022-05-11 11:01 UTC, TonyTramb commented on data/payment_services.json
> +        "regexp": "\/^\\d{1,10}$\/",
![image](https://user-images.githubusercontent.com/91606148/167834649-23b92c71-67b0-4011-90d3-8c5054d387ec.png)

2022-05-11 11:01 UTC, TonyTramb commented on data/payment_services.json
> +        "regexp": "\/^\\d{1,10}$\/",
надо подправить задачу

2022-05-11 11:01 UTC, TonyTramb commented on data/payment_services.json
> +        "example": "Anna"
лучше John Doe )

2022-05-11 11:03 UTC, TonyTramb commented on data/payment_methods.json
> +    "vendor": "PicPay",
picpay

2022-05-11 11:06 UTC, TonyTramb commented on data/payment_services.json
> +    "amount_max": 1000000,
amount_max ставим чтобы было +-100 000 USD
тут будет 500000

2022-05-11 11:06 UTC, TonyTramb commented on data/payment_services.json
> +        "regexp": "\/^\\d{1,10}$\/",
по аналогии с тем,что выше

2022-05-11 11:07 UTC, TonyTramb commented on data/payment_services.json
> +        "example": "Anna"
John Doe

2022-05-11 11:12 UTC, TonyTramb commented on data/payment_services.json
> +        "example": "Anna"
Увидел,что взяла с доки
Но сервис может будем ещё в каком-то коннекторе использовать

2022-05-11 19:10 UTC, michaelkuzyk requested changes

2022-05-11 19:10 UTC, michaelkuzyk commented on data/payment_services.json
> +        "key": "customer_phone",
phone. (vodacom_tzs_invoice - як приклад для всього)

2022-05-11 19:10 UTC, michaelkuzyk commented on data/payment_services.json
> +        "key": "customer_email",
email.  (ingbankpl_pln_hpp як приклад для всього)

2022-05-11 19:10 UTC, michaelkuzyk commented on data/payment_services.json
> +        "key": "customer_first_name",
payer_first_name, payer_last_name

2022-05-11 19:10 UTC, michaelkuzyk commented on data/payment_services.json
> +        "key": "customer_first_name",
bank_transfer_usd_hpp

2022-05-11 19:10 UTC, michaelkuzyk commented on data/payment_services.json
> +        "key": "customer_phone",
аналогічні коменти як до попереднього

2022-05-12 08:37 UTC, michaelkuzyk approved these changes

2022-05-12 08:38 UTC, merged