PC-9539: add kvitum payout method and services
openfintechio/openfintech pull request #757
Opened 2022-05-27 12:21 UTC by Maxym2244

2022-05-31 10:17 UTC, TonyTramb commented on data/payout_services.json
> +    "amount_max": "10000.00"
100000

2022-05-31 10:17 UTC, TonyTramb commented on data/payout_services.json
> +    "amount_max": "10000.00"
100000

2022-05-31 10:18 UTC, TonyTramb commented on data/payout_services.json
> +    "amount_max": "100000.00"
3000000

2022-05-31 10:18 UTC, TonyTramb commented on data/payout_services.json
> +    "amount_max": "500000.00"
40000000

2022-05-31 11:56 UTC, michaelkuzyk requested changes

2022-05-31 11:56 UTC, michaelkuzyk commented on data/payout_services.json
> +          "en": "Wallet Number/Email",
Wallet ID
ID кошелька
ID гаманця

2022-05-31 11:56 UTC, michaelkuzyk commented on data/payout_services.json
> +          "en": "Enter Wallet Number or Email",
номер - ID

2022-05-31 11:56 UTC, michaelkuzyk commented on data/payout_services.json
> +          "en": "Wallet Number/Email",
Wallet ID
ID кошелька
ID гаманця

2022-05-31 11:56 UTC, michaelkuzyk commented on data/payout_services.json
> +          "en": "Enter Wallet Number or Email",
номер - ID

2022-05-31 11:56 UTC, michaelkuzyk commented on data/payout_services.json
> +    "status": "active",
аналогічно

2022-06-01 09:15 UTC, michaelkuzyk requested changes

2022-06-01 09:15 UTC, michaelkuzyk commented on data/payout_services.json
> +          "ru": "Введите номер кошелька или почту",
почту = Email-  не перекладаємо. По всіх сервісах виправити

2022-06-01 09:15 UTC, michaelkuzyk commented on data/payout_services.json
> +          "en": "Enter Wallet ID",
Enter прибрати

2022-06-01 10:17 UTC, michaelkuzyk approved these changes

2022-06-01 10:55 UTC, merged