PC-9684: add oft for v9pay
openfintechio/openfintech pull request #771
Opened 2022-06-17 10:18 UTC by DimaSorokin

2022-06-17 10:21 UTC, TonyTramb commented on data/payment_methods.json
> +    "code": "momo",
duplicate

2022-06-17 10:22 UTC, TonyTramb commented on data/payment_providers.json
> +      "payment_card"
![image](https://user-images.githubusercontent.com/91606148/174279784-232a4647-fd09-46ad-81f6-88327c7cdf55.png)

2022-06-17 10:23 UTC, TonyTramb commented on data/payment_methods.json
> +    "vendor": "viettelpay",
add vendor

2022-06-17 10:24 UTC, TonyTramb commented on data/payment_methods.json
> +    "vendor": "zalopay",
add vendor

2022-06-17 10:24 UTC, TonyTramb commented on data/payment_methods.json
> +    "vendor": "momo",
add vendor

2022-06-17 10:27 UTC, TonyTramb commented on data/vendors.json
> +  {
logo/icon у нас только в png или svg
Надо поискать или на крайний случай форматнуть jpg в png

2022-06-17 10:53 UTC, DimaSorokin commented on data/payment_methods.json
> +    "code": "momo",
+

2022-06-17 10:53 UTC, DimaSorokin commented on data/payment_providers.json
> +      "payment_card"
+

2022-06-17 10:54 UTC, DimaSorokin commented on data/payment_methods.json
> +    "vendor": "viettelpay",
домовилист поки що видалити взагалі вендор в методах

2022-06-17 10:54 UTC, DimaSorokin commented on data/vendors.json
> +  {
+

2022-06-20 09:18 UTC, michaelkuzyk requested changes

2022-06-20 09:18 UTC, michaelkuzyk commented on data/payment_methods.json
> +      "en": "MOMO",
Momo (https://www.crunchbase.com/organization/momo-vn)

2022-06-20 09:39 UTC, michaelkuzyk approved these changes

2022-06-20 09:49 UTC, merged