PC-9873: add cg boombill
openfintechio/openfintech pull request #786
Opened 2022-07-19 08:36 UTC by Marielle89

2022-07-19 08:44 UTC, TonyTramb commented on data/payment_providers.json
> +      "en": "Boom-Bill",
![image](https://user-images.githubusercontent.com/91606148/179707761-078e98ef-9839-4022-8315-79ca8824f643.png)

2022-07-19 08:59 UTC, TonyTramb approved these changes

2022-07-19 15:22 UTC, michaelkuzyk requested changes

2022-07-19 15:22 UTC, michaelkuzyk commented on data/vendors.json
> +      "en": "Boom Bill",
Boom-Bill

2022-07-20 15:15 UTC, michaelkuzyk approved these changes

2022-07-20 15:20 UTC, merged