PC-9993: PG+POG PaySafeCard Add currency
openfintechio/openfintech pull request #802
Opened 2022-08-10 08:20 UTC by VladyslavKL

2022-08-10 11:41 UTC, TonyTramb commented on data/payment_services.json
> +    "amount_max": 1000000
2000000

2022-08-10 11:46 UTC, TonyTramb approved these changes

2022-08-10 18:16 UTC, michaelkuzyk requested changes

2022-08-10 18:16 UTC, michaelkuzyk commented on data/payment_services.json
> +    "method": "paysafecash",
мінус палець Антону

2022-08-11 08:12 UTC, michaelkuzyk approved these changes

2022-08-11 08:12 UTC, merged