Add Vevopay provider
openfintechio/openfintech pull request #923
Opened 2022-11-22 16:48 UTC by TonyTramb

2022-11-25 09:35 UTC, michaelkuzyk requested changes

2022-11-25 09:35 UTC, michaelkuzyk commented on data/payout_methods.json
> +      "en": "Payfix"
PayFix

2022-11-25 09:35 UTC, michaelkuzyk commented on data/payout_methods.json
> +      "en": "Fups"
FUPS

2022-11-25 09:35 UTC, michaelkuzyk commented on data/payout_methods.json
> +    "category": "digital_wallet",
виглядає по гуглу наче пос термінали. Треба більше інфи шо за метод

2022-11-25 09:35 UTC, michaelkuzyk commented on data/payout_services.json
> +        "regexp": "\/^[0-9]{5,100}$\/",
перевірити зміну нижньої межі з 1 на 5, чи не буде проблем

2022-11-25 09:35 UTC, michaelkuzyk commented on data/payout_services.json
> +    "code": "mefete_try",
всі сервіси крім bank_tranfer  -  перевірити точно beneficiary name  - чи це не кастомер ( чи дійсно прив'язка йде не до юзера, а саме до платіжного інструменту), щоб не сувати в сервіс філди

2022-11-25 11:59 UTC, TonyTramb commented on data/payout_methods.json
> +    "category": "digital_wallet",
https://cmtcuzdan.com/

2022-11-25 12:11 UTC, TonyTramb commented on data/payout_services.json
> +    "code": "mefete_try",
ну выглядит как сервис филд,не знаю как это проверить - дока максимально неинформативная

2022-11-28 10:15 UTC, TonyTramb commented on data/payout_services.json
> +    "code": "mefete_try",
![image](https://user-images.githubusercontent.com/91606148/204252325-7d46f9eb-31dd-4d01-918c-7e7105258900.png)

как я понял, это всё-таки реквезиты кошелька

2022-11-28 13:39 UTC, michaelkuzyk commented on data/payout_services.json
> +    "code": "mefete_try",
валідно

2022-11-28 13:41 UTC, michaelkuzyk approved these changes

2022-11-28 13:56 UTC, merged